import Head from "next/head";
import Image from "next/image";
import { Plus_Jakarta_Sans } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Highlight from "react-highlight";
import "highlight.js/styles/base16/ir-black.css";

const plusJakartaSans = Plus_Jakarta_Sans({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>SliceSplice</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={[styles.main, plusJakartaSans.className].join(" ")}>
        <div className={styles.header}>
          <h1 className={styles.h1}>Slice or Splice?</h1>
          <p className={styles.description}>Which should you use?</p>
        </div>
        <div className={[styles.body, styles.u_contentWidth].join(" ")}>
          <p className={styles.paragraph}>
            The slice() method in JavaScript is used to extract a section of an
            array and return it as a new array, without modifying the original
            array. The method takes two arguments, the first is the starting
            index and the second is the ending index (not included) of the
            section to be extracted.
            <br />
            <br />
            The splice() method, on the other hand, is used to add or remove
            elements from an array. It takes three arguments, the first is the
            starting index, the second is the number of elements to be removed,
            and the third is the element(s) to be added. This method modifies
            the original array.
            <br />
            <br />
            Let&apos;s say we have this array of todos:
          </p>
          <Highlight className="language-javascript">
            {`const todos = [
  "Follow @ThePrimeagen on Twitter", 
  "Watch Theos newest video", 
  "Learn the difference between slice and splice"
];`}
          </Highlight>
          <p className={styles.paragraph}>What can we do with slice(...)?</p>
          <Highlight className="language-javascript">
            {`const sliceResult = todos.slice(0, 2);

console.log(sliceResult); 
// Output: ["Follow @ThePrimeagen on Twitter", "Watch Theos newest video"]

console.log(todos); 
// Output: ["Follow @ThePrimeagen on Twitter", "Watch Theos newest video", "Learn the difference between slice and splice"]
`}
          </Highlight>
          <p className={styles.paragraph}>
            See how the original array wasn&apos;t modified?
            <br />
            <br />
            And now splice(...)
          </p>
          <Highlight className="language-javascript">
            {`const spliceResult = tasks.splice(2, 1, 'Call Elon');

console.log(spliceResult);
// Output: ["Learn the difference between slice and splice"]

console.log(tasks);
// Output: ["Follow @ThePrimeagen on Twitter", "Watch Theos newest video", "Call Elon"]
`}
          </Highlight>
          <p className={styles.paragraph}>
            In summary, slice() creates a new array with a section of the
            original array, while splice() modifies the original array by adding
            or removing elements.
          </p>
        </div>
      </main>
    </>
  );
}
